#!/bin/sh -efu

. shell-error
. shell-signal

TEST=

cwd="$(readlink -ev "$0")"
cwd="${0%/*}"

. "$cwd/charon-sh-config"
. "$cwd/charon-sh-functions"

NUM="$1"; shift
REPO="$1"; shift
MTIME="$1"; shift
TYPE="$1"; shift
GITDIR="$1"; shift

reponame="${REPO%.git}"

remote="git@github.com:$GITHUB_ORG/$reponame"

workdir=
exit_handler()
{
	[ -z "$workdir" ] || rm -rf -- "$workdir"
}

git_push()
{
	$TEST git --git-dir="$GITDIR" push -q "$remote" "$name:$target" 2>&1 ||
		{
			printf '%s\n' "$name:$target" >> "$workdir/error.push"
			return 1
		}
}

git_push_branch()
{
	local name="$1"
	local target="${name#refs/heads/}"

	case "$target" in
		*/*|[45].[0-9]|p5)
			return 0
			;;
	esac

	target="repository/$repotype/$target"

	! grep -F -xqs "refs/heads/$target" "$LOCKDIR/$REPO/heads" ||
		return 0

	log 'uploading %s (%s) head %-30s -> %s' "$reponame" "$repotype" "$name" "$target"
	{
		! git_push ||
			printf '%s\n' "refs/heads/$target" >>"$LOCKDIR/$REPO/heads"
	} |
		grep -v -e '^remote:' ||:
}

git_push_tag()
{
	local name="$1"
	local target="${name#refs/tags/}"

	case "$target" in
		*-alt[0-9]*)
			;;
		gb-*|*)
			return 0
			;;
	esac

	! grep -F -xqs "$name" "$LOCKDIR/$REPO/tags" ||
		return 0

	log 'uploading %s (%s) tag  %-30s -> %s' "$reponame" "$repotype" "$name" "$target"

	! git_push ||
		printf '%s\n' "$name" >>"$LOCKDIR/$REPO/tags"
}

if [ ! -d "$GITDIR" ]; then
	log 'not directory: %s' "$GITDIR"
	exit 1
fi

repotype=
case "$TYPE" in
	1) repotype='srpms' ;;
	2) repotype='gears' ;;
	*)
		log 'unknown repository type=%s: %s' "$TYPE" "$GITDIR"
		exit 1
	;;
esac

log 'pushing changes from %s' "$GITDIR"

workdir="$(mktemp -d "$TEMPDIR/$PROG.XXXXXXXXX")"
set_cleanup_handler exit_handler

if [ ! -e "$LOCKDIR/$REPO/heads"  ]; then
	git ls-remote --heads "$remote" |
		cut -f2 > "$LOCKDIR/$REPO/heads"
fi

if [ ! -e "$LOCKDIR/$REPO/tags"  ]; then
	git ls-remote --tags "$remote" |
		sed -n \
			-e '/^.*\^{}$/d' \
			-e 's/^[^[:space:]]\+[[:space:]]\(.*\)$/\1/p' \
		> "$LOCKDIR/$REPO/tags"
fi

git --git-dir="$GITDIR" rev-parse --symbolic-full-name --tags='*' |
	sort -ro "$workdir/tag-refs"

while read -r name; do
	git_push_tag "$name" ||:
done < "$workdir/tag-refs"

git --git-dir="$GITDIR" rev-parse --symbolic-full-name --branches='*' |
	sort -ro "$workdir/head-refs"

sisyphus_repo='refs/heads/sisyphus'

! grep -F -m1 -xqs "$sisyphus_repo" "$workdir/head-refs" ||
	git_push_branch "$sisyphus_repo" ||:

while read -r name; do
	[ "$name" != "$sisyphus_repo" ] ||
		continue
	git_push_branch "$name" ||:
done < "$workdir/head-refs"

if [ -f "$workdir/error.push" ]; then
	:> "$TEMPDIR/failed"
	exit
fi

digest="$(printf '%s' "$TYPE:$REPO" | sha256sum)"
digest="${digest%% *}"
suffix="${digest#??}"
subdir="${digest%$suffix}/$suffix"

mkdir -p -- "$STATEDIR/$subdir"

printf '%s\t%s\t%s\t%s\n' "$REPO" "$MTIME" "$TYPE" "$GITDIR" > "$STATEDIR/$subdir/state"
