#!/bin/sh -efu

cwd="$(readlink -ev "$0")"
cwd="${0%/*}"

. "$cwd/charon-sh-config"
. "$cwd/charon-sh-functions"
. "$cwd/charon-sh-github-functions"

[ -f "$GITHUB_TOKEN" ] ||
	fatal "github token required"

github_api_get "$1"

printf '=== HEADERS ===\n'
cat "$TEMPDIR/github-headers"

printf '=== BODY ===\n'
cat "$TEMPDIR/github-body"
