#!/bin/sh

MAX_PUSHERS=10

ARCHIVEDIR='/archive_git'
BASEDIR='/home/legion/github-sync'

TEMPDIR="$BASEDIR/tmp"
DATADIR="$BASEDIR/data"
LOGDIR="$BASEDIR/logs"
LOCKDIR="$TEMPDIR/locks"
STATEDIR="$DATADIR/state"

old_state="$DATADIR/repos.prv"
cur_state="$DATADIR/repos.cur"

GITHUB_URL='https://api.github.com'
GITHUB_ORG='alt-packages'

GITHUB_TOKEN="$BASEDIR/data/github-token"
